var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database('./controllers/SSNOC.DB');

db.serialize(function() {

    db.exec("DROP TABLE IF EXISTS USER;DROP TABLE IF EXISTS USERPUBLICMESSAGEHISTORY;DROP TABLE IF EXISTS USERPRIVATEMESSAGEHISTORY;DROP TABLE IF EXISTS USERANNOUNCEMENTHISTORY;DROP TABLE IF EXISTS USERSTATUSHISTORY;")


    db.exec("CREATE TABLE USER(USERNAME TEXT PRIMARY KEY, PASSWORD TEXT, ISADMIN BOOLEAN, ISONLINE BOOLEAN, STATUS TEXT, STATUSDATETIME TEXT, CREATEDAT TEXT, LASTLOGINAT TEXT);");
    db.exec("CREATE TABLE USERPUBLICMESSAGEHISTORY(ID INTEGER PRIMARY KEY, USERNAME TEXT, MESSAGE TEXT, DATETIME TEXT,FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME));");
    db.exec("CREATE TABLE USERPRIVATEMESSAGEHISTORY(ID INTEGER PRIMARY KEY, SENDERUSERNAME TEXT, RECEIVERUSERNAME TEXT,MESSAGE TEXT, DATETIME TEXT,FOREIGN KEY(SENDERUSERNAME) REFERENCES USER(USERNAME), FOREIGN KEY(RECEIVERUSERNAME) REFERENCES USER(USERNAME));");
    db.exec("CREATE TABLE USERANNOUNCEMENTHISTORY(ID INTEGER PRIMARY KEY, USERNAME TEXT, MESSAGE TEXT, DATETIME TEXT, FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME));");
    db.exec("CREATE TABLE USERSTATUSHISTORY(ID INTEGER PRIMARY KEY, USERNAME TEXT, STATUS TEXT, UPDATEDAT TEXT, FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME));");
});
db.close();
